### PR TITLE
Feature/jenkins 66322 prepare for upgraded guava

### PR DESCRIPTION
**Pull request by simschla**
Reimplement PR#6 and modernize pom.

### CODE REVIEW

**Review by basil — APPROVED** [review]
Nice job modernizing this plugin! Ideally, we would also add a `Jenkinsfile` to this repository and ensure that the CI build is passing, as well as moving the documentation from the wiki to `README.md`. Let me know if you need any advice about how to do that.

**Comment by simschla** [comment]
@basil I'll gladly do that. Can you point me to the documentation of these aspects (CI-build and moving the documentation).

**Comment by basil** [comment]
For the documentation, start by merging PR #5. That will take care of the docs. :-)

For the build/CI, start by rebasing this commit on top of #4 and then add a `Jenkinsfile`. For an example, take a look at jenkinsci/http-request-plugin#68 which I refreshed about two weeks ago. In that PR, I added a `Jenkinsfile` like

```
/*
 * See the documentation for more options:
 * https://github.com/jenkins-infra/pipeline-library/
 */
buildPlugin(useAci: true, configurations: [
  // Test the long-term support end of the compatibility spectrum (i.e., the minimum required
  // Jenkins version).
  [ platform: 'linux', jdk: '8', jenkins: null ],

  // Test the common case (i.e., a recent LTS release).
  [ platform: 'linux', jdk: '8', jenkins: '2.289.3' ],

  // Test the bleeding edge of the compatibility spectrum (i.e., the latest supported Java runtime).
  [ platform: 'linux', jdk: '11', jenkins: '2.289.3' ],
])
```

to run three parallel builds. You might do similar. Once that is done, you should get a CI run and a green or red checkmark in the PR, depending on whether the build passed or failed.

**Review by basil — APPROVED** [review]
Great job refreshing this plugin!

**Comment by basil** [comment]
@simschla :ship: :it: ?

**Pull request merged**
